name: apod
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_modular: ^6.3.2
  mobx: ^2.3.0
  flutter_mobx: ^2.2.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  mobx_codegen: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Nasalization
      fonts:
        - asset: fonts/nasa/nasalization-rg.otf

    - family: Poppins
      fonts:
        - asset: fonts/poppins/Poppins-Black.ttf
        - asset: fonts/poppins/Poppins-Bold.ttf
        - asset: fonts/poppins/Poppins-ExtraBold.ttf
        - asset: fonts/poppins/Poppins-ExtraLight.ttf
        - asset: fonts/poppins/Poppins-Light.ttf
        - asset: fonts/poppins/Poppins-Medium.ttf
        - asset: fonts/poppins/Poppins-Regular.ttf
        - asset: fonts/poppins/Poppins-SemiBold.ttf
        - asset: fonts/poppins/Poppins-Thin.ttf